#!/usr/bin/env bash
# proxy config

apt update
apt upgrade -y
apt install -y haproxy

printf %s "
        frontend http_front
		bind *:80
		stats uri /haproxy?stats
		default_backend http_back

        backend http_back
		balance roundrobin
		server 4377-web-01 54.226.206.178 check
		server 4377-web-02 50.19.175.7 check
" >> /etc/haproxy/haproxy.cfg

systemctl restart haproxy
