#!/usr/bin/env bash
# proxy config

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 4377-lb-01
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 4377-web-01 54.226.206.178 check
        server 4377-web-02 50.19.175.7 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
