#!/usr/bin/env bash
# read
while IFS=":" read -r username groupid homedir cmdshell userid password user_id_info
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $cmdshell. $userid's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < /etc/passwd
